spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: ture
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp: ${JWT_ACCESS_EXP:3600}
  refresh-exp: ${JWT_REFRESH_EXP:1209600}